### ISSUE TITLE
Implement WHERE clause

### ISSUE THREAD

**Issue by Sitole** [baraja-core/doctrine-fulltext-search#1]
For example, I want to load articles, but many of them are private, and I have to load them all and select them at the application level, which is both memory and performance intensive.

It would be good to implement a database where clause.
cc @janbarasek

**Comment by janbarasek** [comment]
@Sitole Thanks for suggestion.

I implemented simple logic for user wheres which will be used as AND filters.

You can use array of wheres (strings) or use `SelectorBuilder` class.

Commit: https://github.com/baraja-core/doctrine-fulltext-search/commit/7892fba1a0a95268cde3d2813a76caee98ffaefc

By the way lot of filters can be used by user natively in query which I added by this commit: https://github.com/baraja-core/doctrine-fulltext-search/commit/6abb0350152abbb9bba91a17ed7c9ddd6c1d57d5

Now user can use this filters:

- Exact match in quotes: `"to be or not to be"`
- Negative match: `linux -ubuntu`
- Number interval `2017..2020`.

Thanks.
