### ISSUE TITLE
Missing requirement of ramsey/uuid-doctrine

### ISSUE THREAD

**Issue by FabianKoestring** [baraja-core/doctrine-fulltext-search#17]
Version: 3.0.9

### Bug Description
In `SearchQuery` Type `uuid` is used. 

https://github.com/baraja-core/doctrine-fulltext-search/blob/0ba0f122cc78dbd0a18fe58ff91fc7ef57a48e19/src/Entity/SearchQuery.php#L27

### Possible Solution
Add `"ramsey/uuid-doctrine": "~1.7.0",` to composer require.

**Comment by janbarasek** [comment]
Fixed in version `3.1.0`.

Now it is ok? Please test it.

Thanks.
